---
- name: Generation d'une OpenSSL Certificate Signing Request
  openssl_csr:
          path: /etc/gitlab/ssl/gitlab.example.com.csr
          privatekey_path: /etc/gitlab/ssl/gitlab.example.com.key
          country_name: FR
          organization_name: OpenClassRoom
          email_address: ali.akrour@gmail.com
          common_name: gitlab.example.com

