---
- name: "Modification de l'url externe pour https"
  lineinfile:
          path: /etc/gitlab/gitlab.rb
          regexp: 'external_url ''http:\/\/mygta\.com'''
          line: 'external_url ''https://mygta.com:4443''' 
