---
- name: Generation d'un fichier de certificat PKCS#12 dans le dossier du projet ( VM /vagrant )
  openssl_pkcs12:
          action: export
          path: /vagrant/gitlab.example.com.p12
          friendly_name: gitlab
          privatekey_path: /etc/gitlab/ssl/gitlab.example.com.key
          certificate_path: /etc/gitlab/ssl/gitlab.example.com.crt
          state: present

