---
- name: Generation d'une clé privée et d'une demande de certificat pour le serveur
  shell:
          openssl req -new -sha256 -nodes -out /etc/gitlab/ssl/gitlab.example.com.csr -newkey rsa:2048 -keyout /etc/gitlab/ssl/gitlab.example.com.key -subj "/O=Alinuxien/CN=gitlab.example.com"

