concurrent = 4
check_interval = 0

[[runners]]
  name = "myrunner"
  url = "https://gitlab.example.com:4443/"
  token = "DS6hzS5JcRb-jzAt27DW"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "alpine:3.12.0"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    extra_hosts = ["gitlab.example.com:10.0.2.15"]
