stages:
  - build
  - deploy
  
build_job:
  stage: build
  script:
    - pelican content -o output -s pelicanconf.py
  artifacts:
    paths:
        - output
        
deploy_job:
  stage: deploy
  script:
  - git remote remove gh_pages
  - git remote add gh_pages -t $GH_PAGES_BRANCH https://x-access-token:$GITHUB_ACCESS_TOKEN@github.com/$GITHUB_USERNAME/$GITHUB_REPO_NAME.git
  - git pull gh_pages
  - git merge -s ours gh_pages/$GH_PAGES_BRANCH
  - git config --global user.email "$GITHUB_EMAIL"
  - git config --global user.name "$GITHUB_NAME"
  - git add -A
  - git commit --allow-empty -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
  - git push gh_pages HEAD:$GH_PAGES_BRANCH
  only:
  - master
  when: manual
  
